name: Apply Patch
on:
  workflow_dispatch:
    inputs:
      patch:
        description: "Unified diff patch"
        required: true
        type: string
permissions:
  contents: write
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply patch
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cat > patch.diff << 'PATCH'
${{ github.event.inputs.patch }}
PATCH
          git apply --whitespace=fix patch.diff
          git add -A
          git commit -m "Apply patch via workflow" || echo "No changes to commit"
          git push
